[package]
name = "bplus_tree_cmp"
version = "0.1.0"
edition = "2024"
description = """
A B+tree ordered entirely by a comparer either supplied by user or deduced.
"""
license = "MIT OR Apache-2.0"

[lib]
name = "bplustree_cmp"
path = "src/lib.rs"

[dependencies]
slab = { version = "0.4.12", default-features = false }

[dev-dependencies]
rand = "0.9"
